version: '3.9'
services:
  crud:
    build:
      context: .
      dockerfile: cmd/crud/Dockerfile
    ports:
      - 9999:9999
    restart: on-failure
    depends_on:
      - mongo
      - zookeeper
      - broker
    networks:
      - crud

  mongo:
    image: mongo:4.4
    command: "mongod --dbpath /data/db"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
    networks:
      - crud
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    restart: on-failure
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - crud
  broker:
    image: confluentinc/cp-kafka:7.0.1
    container_name: broker
    restart: on-failure
    depends_on:
      - zookeeper
    networks:
      - crud
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

networks:
  crud:
    name: crud