version: '3.9'
services:
  crud:
    build:
      context: .
      dockerfile: cmd/crud/Dockerfile
    ports:
      - 9999:9999
  mongo:
    image: mongo:4.4
    command: "mongod --dbpath /data/db"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
      - MONGO_INITDB_DATABASE=company
      - MONGO_INITDB_USER=mongodb
      - MONGO_INITDB_PWD=mongodb
    volumes:
      - .artifacts/mongo/:/data/db
